applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name="empleados_all"),
    path('listar-area/<shortName>/', views.ListByAreaEmpleado.as_view(),
         name='empleados_area'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetallesView.as_view()
         , name = 'empleado_detail'),
    path('agregar-empleado/', views.EmpleadoCreateView.as_view(), name="registrar_empleado"),
    path('success/', views.SuccessView.as_view(), name= 'correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name= 'modificar_empleado'),
    path('eliminar-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name= 'eliminar_empleado'),
    path('lista-empleados-admin', views.ListAllEmpleadosAdmin.as_view(), name= 'empleados_admin'),
]

empleadosPr/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de las apps
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models

from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    def __str__(self):
        return self.habilidad

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades de empleado'

class Empleado(models.Model):
    trabajos = [
        ['0','Contador'],['1','Administrador'],
        ['2', 'Economista'], ['3', 'Otro']
    ]
    firstName = models.CharField('Nombres', max_length=60)
    lastName = models.CharField('Apellidos', max_length=60)
    fullName = models.CharField('Nombre completo', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=1, choices=trabajos)
    department = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', null=True, blank=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'El empleado'
        verbose_name_plural = 'Los empleados'
        ordering = ['job']
        unique_together = ('firstName', 'lastName', 'department')

    def __str__(self):
        return str(self.id) + ' ' + self.firstName + ' ' + self.lastName

applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    """Form definition for Empleado."""

    class Meta:
        """Meta definition for Empleadoform."""

        model = Empleado
        fields = (
            'firstName',
            'lastName',
            'job',
            'department',
            'avatar',
            'habilidades',
            'hoja_vida',
        )
        widgets = {
            'habilidades' : forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
import re

from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)
from .models import Empleado, Habilidades
from .forms import EmpleadoForm


# Create your views here.

class InicioView(TemplateView):
    """ Vista que carga la pagina de inicio"""
    template_name = 'inicio.html'

class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 5
    ordering = "firstName"
    
    def get_queryset(self):
        palabraClave = self.request.GET.get('nombre', '')
        lista = Empleado.objects.filter(
            firstName__icontains= palabraClave
        )
        print(lista)
        return lista


class ListAllEmpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    paginate_by = 10
    ordering = "firstName"
    context_object_name = 'empleados'
    model = Empleado


class ListByAreaEmpleado(ListView):
    template_name = 'persona/listar-por-area.html'

    def get_queryset(self):
        area = self.kwargs['shortName']
        lista = Empleado.objects.filter(
            department__shortName=area
        )
        return lista


class ListEmpleadosByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabraClave = self.request.GET.get('nombre', '')
        lista = Empleado.objects.filter(
            firstName=palabraClave
        )
        return lista


class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        idEmpleado = self.request.GET.get('idEmpleado')
        lista = []
        if (idEmpleado != None and re.match(r'^\d+$', idEmpleado)):
            try:
                empleado = Empleado.objects.get(id=idEmpleado)
                lista = empleado.habilidades.all()
            except ObjectDoesNotExist:
                print('Query no encontrado')
        return lista


class EmpleadoDetallesView(DetailView):
    model = Empleado
    template_name = 'persona/detalle_empleado.html'

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetallesView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context


class SuccessView(TemplateView):
    template_name = 'persona/success.html'


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = 'persona/add.html'
    form_class = EmpleadoForm
    # ponemos la url a donde debe de ir
    success_url = reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        # lógica del proceso
        empleado = form.save(commit=False)
        empleado.fullName = empleado.firstName + " " + empleado.lastName
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    template_name = 'persona/update.html'
    model = Empleado
    fields = ('firstName', 'lastName', 'avatar', 'job', 'department', 'habilidades', 'hoja_vida')
    success_url = reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        # lógica del proceso
        print('FORM VALID')
        return super(EmpleadoUpdateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        print('POST')
        return super().post(request, *args, **kwargs)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    context_object_name = 'empleado'
    template_name = 'persona/delete.html'
    success_url = reverse_lazy('persona_app:empleados_admin')

templates/persona/add.html
{% extends 'base.html' %}

{% block titulo %} Registrar Empleado {% endblock titulo %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Ingresar Empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.firstName}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.lastName}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label class="top">Imagen de perfil:
                    {{form.avatar}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                    {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{form.department}}
                </label>
            </div>
            <div class="cell">
                <label>Habilidades:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label >Hoja de vida:
                    {{form.hoja_vida}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button class="button success" type="submit">Agregar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}
    

templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>
<form method="get">{% csrf_token %}
    <input type="text" id="nombre" name="nombre" placeholder="Ingrese nombre aquí">
    <button type="submit">Buscar</button>
</form>
<ul>
    {% for empleado in empleados %}
        <li>{{empleado}}</li>
    {% endfor %}

</ul>

templates/persona/delete.html
{% extends 'base.html' %}

{% block titulo %} Eliminar Empleado {% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-margin-x">
        <h1 class="cell">Eliminar empleado: {{empleado.firstName}} {{empleado.lastName}}</h1>

        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout secondary">
                <p>¿Desea eliminar a este empleado?</p>
                <button class="button warning" type="submit">Confirmar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/persona/detalle_empleado.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} {{object.fullName}} {% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="card large-6 cell" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
            <!--Como recuperas de un campo choices que es un diccionario en el modelo-->  
            {{object.get_job_display}}
            </div>
            
            {% if empleado.avatar %}
               <img src="{{object.avatar.url}}">
            {% else %}
               <img src="{% static 'img/At-the-Office-Mac-Apple-Wallpapers-Creative-Planning-2982192420.jpeg' %}">
            {% endif %}
            <div class="card-section">
              <h4>{{object.fullName}}</h4>
              <p>{{object.firstName}}</p>
              <p>{{object.lastName}}</p>
              <p>{{object.department.shortName}}</p>
              <p><span class="label">Habilidades</span></p>
              <ul class="vertical menu">
                  <!--como recuperas el arreglo de un campo many to many-->
                  {% for habilidad in object.habilidades.all %}
                      <li>{{habilidad}}</li>
                  {% endfor %}      
              </ul>
              <p>{{object.hoja_vida}}</p>
            </div>
          </div>
    </div>
</div>
{% endblock content %}

templates/persona/habilidades.html
<h1>Habilidades del empleado</h1>
<form method="get">{% csrf_token %}
    <input type="text" id="idEmpleado" name="idEmpleado" placeholder="Ingrese el id del empleado">
    <button type="submit">Buscar</button>
</form>

<ul>

{% for habilidad in habilidades %}
    <li>{{habilidad}}</li>
{% endfor %}

</ul>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block titulo %}
    Lista de empleados
{% endblock titulo %}
    
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
            <div class="cell large-7 medium-8">
                <input type="text" id="nombre" name="nombre" placeholder="Buscar empleado">
            </div>
            <div class="cell large-2 medium-3">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>Nombres</th>
                    <th width="150">Apellidos</th>
                    <th width="150">Departamento</th>
                    <th width="100">Acción</th>
                  </tr>
                </thead>
                <tbody>
                {% for empleado in object_list %}
                  <tr>
                    <td>{{empleado.id}}</td>
                    <td>{{empleado.firstName}}</td>
                    <td>{{empleado.lastName}}</td>
                    <td>{{empleado.department.shortName}}</td>
                      <td><a class="button warning" href="{% url 'persona_app:empleado_detail' empleado.id %}">Ver</a></td>
                  </tr> 
                {% endfor %}
                </tbody>
              </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Anterior</li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}
                            
                            {% ifequal pagina page_obj.number %} 
                                <li class="current">
                                    <a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a>
                                </li>
                            {% else %}
                            <li><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li> 
                            {% endifequal %}   
                        {% endfor %}
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente</li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
        
    </div>
</div>
{% endblock content %}

templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block titulo %}
    Lista de empleados
{% endblock titulo %}
    
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">ID</th>
                    <th>Nombres</th>
                    <th width="150">Apellidos</th>
                    <th width="150">Departamento</th>
                    <th width="100">Acción</th>
                  </tr>
                </thead>
                <tbody>
                {% for empleado in object_list %}
                  <tr>
                    <td>{{empleado.id}}</td>
                    <td>{{empleado.firstName}}</td>
                    <td>{{empleado.lastName}}</td>
                    <td>{{empleado.department.shortName}}</td>
                      <td><a class="button success" href="{% url 'persona_app:modificar_empleado' empleado.id %}">Editar</a></td>
                      <td><a class="button alert" href="{% url 'persona_app:eliminar_empleado' empleado.id %}">Eliminar</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Anterior</li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}
                            
                            {% ifequal pagina page_obj.number %} 
                                <li class="current">
                                    <a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a>
                                </li>
                            {% else %}
                            <li><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li> 
                            {% endifequal %}   
                        {% endfor %}
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente</li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
        
    </div>
</div>
{% endblock content %}

templates/persona/listar-por-area.html
{% extends 'base.html' %}

{% block titulo %} Lista de empleados por area {% endblock titulo %}  

{% block content %}
{% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Empleados por área</h1>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="100">Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for empleado in object_list %}
                        <tr>
                        <td>{{empleado.id}}</td>
                        <td>{{empleado.firstName}}</td>
                        <td>{{empleado.lastName}}</td>
                        <td>{{empleado.department.shortName}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' empleado.id %}">Ver</a></td>
                        </tr> 
                    {% endfor %}
                    </tbody>
                    </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/persona/success.html
<h1>Se guardó correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}

{% block titulo %} Editar Empleado {% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">   
            <h1 class="cell">Modificar empleado</h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <div class="cell medium-6 large-6">
                        <label>
                            Nombres:
                            {{form.firstName}}
                        </label>
                    </div>
                    <div class="cell medium-6 large-6">
                        <label>
                            Apellidos:
                            {{form.lastName}}
                        </label>
                    </div>
                    <div class="medium-12 cell">
                        <label class="top">Imagen de perfil:
                            {{form.avatar}}
                        </label>
                    </div>
                    <div class="cell medium-6 large-6">
                        <label>
                            Trabajo:
                            {{form.job}}
                        </label>
                    </div>
                    <div class="cell medium-6 large-6">
                        <label>
                            Area:
                            {{form.department}}
                        </label>
                    </div>
                    <div class="cell">
                        <label>
                            habilidades:
                            {{form.habilidades}}
                        </label>
                    </div>
                    <div class="cell">
                        <label>
                            Detalles:
                            {{form.hoja_vida}}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="success button">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}