applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('agregar-departamento/', views.CreateDepartamentoView.as_view(), name='nuevo_departamento'),
    path('departamento-lista/', views.DepartamentoListView.as_view(), name='department_list'),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name="empleados_all"),
    path('listar-area/<shortName>/', views.ListByAreaEmpleado.as_view(),
         name='empleados_area'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetallesView.as_view()
         , name = 'empleado_detail'),
    path('agregar-empleado/', views.EmpleadoCreateView.as_view(), name="registrar_empleado"),
    path('success/', views.SuccessView.as_view(), name= 'correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name= 'modificar_empleado'),
    path('eliminar-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name= 'eliminar_empleado'),
    path('lista-empleados-admin', views.ListAllEmpleadosAdmin.as_view(), name= 'empleados_admin'),
]

empleadosPr/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de las apps
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamento_app:department_list' %}">Departamentos</a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Agregar Departamento</a></li>
        <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <li><a type="button" class="button" href="{% url 'persona_app:registrar_empleado' %}">Registrar nuevo</a></li>
      </ul>
    </div>
  </div>