applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('agregar-departamento/', views.CreateDepartamentoView.as_view(), name='nuevo_departamento'),
    path('departamento-lista/', views.DepartamentoListView.as_view(), name='department_list'),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name="empleados_all"),
    path('listar-area/<shortName>/', views.ListByAreaEmpleado.as_view(),
         name='empleados_area'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetallesView.as_view()
         , name = 'empleado_detail'),
    path('agregar-empleado/', views.EmpleadoCreateView.as_view(), name="registrar_empleado"),
    path('success/', views.SuccessView.as_view(), name= 'correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name= 'modificar_empleado'),
    path('eliminar-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name= 'eliminar_empleado'),
    path('lista-empleados-admin', views.ListAllEmpleadosAdmin.as_view(), name= 'empleados_admin'),
]

empleadosPr/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    #incluimos las urls de las apps
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shortName = models.CharField('Nombre Corto', max_length=20)
    active = models.BooleanField('Activado', default=True)

    class Meta:
        verbose_name = 'Mi departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['name']
        #Evita los registros que tengan los mismos valores en ambos campos
        #como una llave primaria compuesta
        unique_together = ('name', 'shortName')

    def __str__(self):
        return self.name

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortName = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import FormView
# Create your views here.
from .forms import NewDepartamentoForm
from applications.persona.models import Empleado
from .models import Departamento


class CreateDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = reverse_lazy('departamento_app:department_list')

    def form_valid(self, form):
        dep = Departamento(
            name= form.cleaned_data['departamento'],
            shortName = form.cleaned_data['shortName']
        )
        dep.save()
        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']
        Empleado.objects.create(
            firstName = nombre,
            lastName = apellidos,
            fullName= nombre + " " + apellidos,
            job='1',
            department =dep
        )
        return super(CreateDepartamentoView,self).form_valid(form)


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"

templates/departamento/lista.html
{% extends 'base.html' %}

{% block titulo %} Lista departamentos {% endblock titulo %}

{% block content %}
{% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in object_list %}                           
                        <tr>
                            <td>{{departamento.name}}</td>
                            <td>{{departamento.shortName}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shortName %}">Ver empleados</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block titulo %} Registrar Departamento {% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
           
            <h3 class="cell">Datos Empleado</h3>
            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.apellidos}}
                </label>
            </div>
            <h3 class="cell">Datos Departamento</h3>
            <div class="medium-6 cell">
                <label>Nombre de departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Nombre corto de departamento:
                    {{form.shortName}}
                </label>
            </div>
            <div class="medium-6 cell">
                <button class="button success" type="submit">Agregar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}